baseURL: https://wmrra.com
languageCode: en-us
title: Washington Motorcycle Road Racing Association
theme: wmrra-com-theme
#disablePathToLower: true
pagination:
  pagerSize: 12

params:
  dateFormat: "January 1, 2021"

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true